version: "3.7"
services:
  elasticsearch:
    build: ./elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node

  web:
    build: ./
    ports:
      - 3000:3000
    command: ./wait-for.sh elasticsearch:9200 -- node app.js
    environment:
      - ES_HOST=elasticsearch:9200
