version: "3.7"
services:
  elasticsearch:
    build: ./elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    restart: always
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data:rw

  web:
    build: ./
    ports:
      - 3000:3000
    environment:
      - ES_HOST=elasticsearch:9200
    restart: always
    command: node --unhandled-rejections=strict app.js

volumes: 
  - elasticsearch: